stakater/saap-docs

content/for-delivery-engineers/gitops/application-onboarding.md
content/for-delivery-engineers/gitops/environments.md
content/for-delivery-engineers/gitops/github.md
content/legal-documents/pp.md
mkdocs.yml

Also enabling strict processing of config

Privacy policy and TOC fixes

---

content/for-delivery-engineers/gitops/creating-gitops-structure.md

namespace changes are done for the Apps repo ArgoCD application.

Fixes for namespace

---

content/for-delivery-engineers/gitops/creating-gitops-structure.md

ArgoCD Application for App repo path fixed

ArgoCD app fixes

---

content/for-delivery-engineers/gitops/application-onboarding.md

Application Dockerfile path mentioned.

Dockerfile path mentioned

---

content/for-delivery-engineers/gitops/application-onboarding.md

"/" removal instruction added as a note while login Docker.

Avoiding errors while login docker

---

content/for-delivery-engineers/how-to-guides/add-a-cluster-task/add-cluster-task.md
content/for-delivery-engineers/tutorials/01-configure-infra-gitops-config/configure-infra-gitops-repo.md
content/for-delivery-engineers/tutorials/02-configure-apps-gitops-config/configure-apps-gitops-repo.md
content/for-delivery-engineers/tutorials/03-deploy-demo-app/deploy-demo-app.md
content/for-delivery-engineers/tutorials/04-add-tekton-pipeline-to-demo-app/add-pipeline.md
mkdocs.yml

add more sections to deleng

---

content/for-delivery-engineers/tutorials/01-configure-infra-gitops-config/configure-infra-gitops-repo.md
content/for-delivery-engineers/tutorials/03-deploy-demo-app/deploy-demo-app.md

The commands to build and push application images are fixed.

Image building and pushing commands fixed

---

content/for-delivery-engineers/tutorials/03-deploy-demo-app/deploy-demo-app.md

Fixed repo name from "stakater-nordmart-review-ui" to "stakater-nordmart-review-web".

Repo name fixed

---

content/for-delivery-engineers/tutorials/02-configure-apps-gitops-config/configure-apps-gitops-repo.md

ArgoCD apps paths and content fixed

argocd apps fixes

---

content/for-administrators/plan-your-environment/sizing.md
mkdocs.yml

remove empty architecture doc

---

content/managed-addons/overview.md
content/managed-addons/volume-expander-operator/overview.md
mkdocs.yml

add volume expander operator

---

content/for-administrators/explanation/number-of-clusters.md
mkdocs.yml

how many clusters

---

content/for-developers/tutorials/outer-loop/add-ci-pipeline/03-create-webhook.md

Notes need to come last as part of steps, and need to have the exact indendation of 4 spaces

Item updates

---

mkdocs.yml

https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#__codelineno-1-3

enable copy code blocks

---

Dockerfile

Updated deployed url path for saap docs in docker file
Fixes # (issue)
UI/UX
Enhancement

[Task] Updated saap docks dockerfile SA 5773

---

theme_override/mkdocs.yml

Updated mkdocs yaml removed unused spaces

[Task[ Update theme saap docs

---

renovate.json

Update the config so it matches releases properly

Renovate config update

---

content/about/service-definition.md
theme_override/mkdocs.yml

add full page on service definition

---

content/legal-documents/dpa.md
content/legal-documents/fa.md
content/legal-documents/nda.md
content/legal-documents/overview.md
content/legal-documents/pp.md
theme_override/mkdocs.yml

add overview page to legal documents so, it's easy to browse

add overview to legal documents

---

content/legal-documents/fa.md
content/legal-documents/overview.md

bring fa to top and fix the rest

fix links and structure

---

content/legal-documents/gtc.md

add link and refine it further

add link in gtc

---

content/legal-documents/fa.md
content/legal-documents/sla.md
theme_override/mkdocs.yml

fix sla docs
